Group17_MVC (2)/Group17_MVC/Group17_MVC/Controllers/QuanlidonhangController.cs
using Group17_MVC;
using System.Linq;
using System.Web.Mvc;

namespace Group17_MVC.Controllers
{
    public class QuanlidonhangController : Controller
    {
        private readonly Nhom17_WedBanSachEntities db = new Nhom17_WedBanSachEntities();

        public ActionResult Index(string searchString)
        {
            var donHangs = string.IsNullOrEmpty(searchString)
                ? db.DonHangs.ToList()
                : db.DonHangs.Where(d => d.MaDonHang.Contains(searchString)).ToList();

            return View(donHangs);
        }

       
        public JsonResult ChiTietDonHang(string maDonHang)
        {
            if (string.IsNullOrEmpty(maDonHang))
            {
                return Json(new { error = "Mã đơn hàng không hợp lệ." }, JsonRequestBehavior.AllowGet);
            }

            var orderDetails = db.ChiTietDonHangs
                                 .Where(c => c.MaDonHang == maDonHang)
                                 .Select(c => new
                                 {
                                     MaDonHang = c.MaDonHang,
                                     NguoiDung = c.DonHang.NguoiDung.HoTen,
                                     ChiTiet = c.DonHang.ChiTietDonHangs.Select(d => new
                                     {
                                         MaSach = d.MaSach,
                                         TenSach = d.Sach.TenSach,
                                         TacGia = d.Sach.TacGia,
                                         SoLuong = d.SoLuong,
                                         GiaBan = d.GiaBan
                                     }).ToList(),
                                     TongTien = c.DonHang.TongTien
                                 })
                                 .FirstOrDefault();

            if (orderDetails == null)
            {
                return Json(new { error = "Không tìm thấy đơn hàng." }, JsonRequestBehavior.AllowGet);
            }

            return Json(orderDetails, JsonRequestBehavior.AllowGet);
        }
    }
}

Group17_MVC (2)/Group17_MVC/Group17_MVC/Controllers/QuanlinguoidungController.cs
using Group17_MVC;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Group17_MVC.Controllers
{
    public class QuanlinguoidungController : Controller
    {
        Nhom17_WedBanSachEntities db = new Nhom17_WedBanSachEntities();
        private static readonly HashSet<string> lockedAccounts = new HashSet<string>();

        public static HashSet<string> GetLockedAccounts()
        {
            return lockedAccounts;
        }

        public ActionResult LockAccount(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                lockedAccounts.Add(id);
            }
            return RedirectToAction("Index");
        }

        public ActionResult UnlockAccount(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                lockedAccounts.Remove(id);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Index(string searchString)
        {
            var nguoidung = string.IsNullOrEmpty(searchString)
                ? db.NguoiDungs.ToList()
                : db.NguoiDungs.Where(d =>
                    d.MaNguoiDung.Contains(searchString) ||
                    d.HoTen.Contains(searchString) ||
                    d.Email.Contains(searchString) ||
                    d.SoDienThoai.Contains(searchString)).ToList();
            ViewBag.LockedAccounts = lockedAccounts;
            ViewBag.SearchString = searchString;
            return View(nguoidung);
        }

        public ActionResult Edit(string id)
        {
            var item = db.NguoiDungs.FirstOrDefault(n => n.MaNguoiDung == id);
            if (item == null)
            {
                return HttpNotFound();
            }

            var roles = new List<SelectListItem>
            {
                new SelectListItem { Text = "Admin", Value = "Admin" },
                new SelectListItem { Text = "KhachHang", Value = "KhachHang" }
            };
            ViewBag.VaiTroList = roles;

            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(NguoiDung model)
        {
            if (ModelState.IsValid)
            {
                var user = db.NguoiDungs.FirstOrDefault(u => u.MaNguoiDung == model.MaNguoiDung);
                if (user != null)
                {
                    user.VaiTro = model.VaiTro;
                    db.Entry(user).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }
        public ActionResult Add()
        {
            
            var roles = new List<SelectListItem>
    {
        new SelectListItem { Text = "Admin", Value = "Admin" },
        new SelectListItem { Text = "KhachHang", Value = "KhachHang" }
    };
            ViewBag.VaiTroList = roles;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(NguoiDung model)
        {
            if (ModelState.IsValid)
            {
                db.NguoiDungs.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(model);
        }

    }
}

Group17_MVC (2)/Group17_MVC/Group17_MVC/Controllers/QuanlisanphamController.cs
using Group17_MVC;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Group17_MVC.Controllers
{
    public class QuanlisanphamController : Controller
    {
        // GET: Admin/Quanlisanpham
        private Nhom17_WedBanSachEntities db = new Nhom17_WedBanSachEntities();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Add()
        {
            using (var context = new Nhom17_WedBanSachEntities())
            {
                var theLoaiList = context.TheLoais
                                     .Select(tl => new SelectListItem
                                     {
                                         Value = tl.MaTheLoai.ToString(),
                                         Text = tl.MaTheLoai.ToString()
                                     }).ToList();

                ViewBag.TheLoaiList = theLoaiList;
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Sach model)
        {
            if (ModelState.IsValid)
            {
                model.NgayTao = DateTime.Now;
                db.Saches.Add(model);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);

        }
        public ActionResult Edit(string id)
        {
            
            var categories = db.TheLoais.ToList();
            ViewBag.TheLoaiList = new SelectList(categories, "MaTheLoai", "TenTheLoai");
            var item = db.Saches.FirstOrDefault(s => s.MaSach == id);

            if (item == null)
            {
                return HttpNotFound();
            }

            return View(item); 
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Sach model)
        {
            if (ModelState.IsValid)
            {
                
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            var categories = db.TheLoais.ToList();
            ViewBag.TheLoaiList = new SelectList(categories, "MaTheLoai", "TenTheLoai");

            return View(model);
        }
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var item = db.Saches.FirstOrDefault(s => s.MaSach == id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            var item = db.Saches.FirstOrDefault(s => s.MaSach == id);
            if (item == null)
            {
                return HttpNotFound();
            }
            db.Saches.Remove(item);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Group17_MVC (2)/Group17_MVC/Group17_MVC/Controllers/ThongkeController.cs
using Group17_MVC;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Group17_MVC.Controllers
{
    public class ThongKeController : Controller
    {
        private Nhom17_WedBanSachEntities db = new Nhom17_WedBanSachEntities();

        public ActionResult Index(string searchQuery)
        {
            int tongnguoidung = db.NguoiDungs.Count();
            ViewBag.Tonguser = tongnguoidung;
            int tongdonhang = db.DonHangs.Count();
            ViewBag.Tongdh = tongdonhang;
            int sachchuadat = db.Saches.Where(s => !s.ChiTietDonHangs.Any()).Count();
            ViewBag.SachChuaDat = sachchuadat;

            var listsach = db.Saches
                .Where(s => !s.ChiTietDonHangs.Any())
                .Select(s => new SachViewModel
                {
                    MaSach = s.MaSach,
                    TenSach = s.TenSach
                });

            if (!string.IsNullOrEmpty(searchQuery))
            {
                listsach = listsach.Where(s => s.MaSach.Contains(searchQuery));
            }

            return View(listsach.ToList());
        }

    }

    public class SachViewModel
    {
        public string MaSach { get; set; }
        public string TenSach { get; set; }
    }
}

Group17_MVC (2)/Group17_MVC/Group17_MVC/Views/Quanlinguoidung/Add.cshtml
@model Group17_MVC.NguoiDung
@{
    ViewBag.Title = "Thêm mới người dùng";
   

@section naviheader {
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="@Url.Action("Index", "Admin")"> Trang chủ</a>
        </li>

        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Thêm mới</a>
        </li>
    </ul>
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Thêm mới người dùng</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Thêm mới</li>
                </ol>
            </div>
        </div>
    </div>
</section>

<!-- Main content -->
<section class="content">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Thông tin người dùng mới</h3>
        </div>
        <div class="card-body">
            @using (Html.BeginForm("Add", "Quanlinguoidung", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(false)

                <div class="form-group">
                    <label for="MaNguoiDung">Mã người dùng</label>
                    @Html.TextBoxFor(x => x.MaNguoiDung, new { @class = "form-control", @placeholder = "Mã người dùng" })
                    @Html.ValidationMessageFor(x => x.MaNguoiDung, null, new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <label for="HoTen">Họ và tên</label>
                    @Html.TextBoxFor(x => x.HoTen, new { @class = "form-control", @placeholder = "Họ và tên" })
                    @Html.ValidationMessageFor(x => x.HoTen, null, new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <label for="Email">Email</label>
                    @Html.TextBoxFor(x => x.Email, new { @class = "form-control", @placeholder = "Email" })
                    @Html.ValidationMessageFor(x => x.Email, null, new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <label for="MatKhau">Mật khẩu</label>
                    @Html.PasswordFor(x => x.MatKhau, new { @class = "form-control", @placeholder = "Mật khẩu" })
                    @Html.ValidationMessageFor(x => x.MatKhau, null, new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <label for="SoDienThoai">Số điện thoại</label>
                    @Html.TextBoxFor(x => x.SoDienThoai, new { @class = "form-control", @placeholder = "Số điện thoại" })
                    @Html.ValidationMessageFor(x => x.SoDienThoai, null, new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <label for="DiaChi">Địa chỉ</label>
                    @Html.TextBoxFor(x => x.DiaChi, new { @class = "form-control", @placeholder = "Địa chỉ" })
                    @Html.ValidationMessageFor(x => x.DiaChi, null, new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <label for="VaiTro">Vai trò</label>
                    @Html.DropDownListFor(x => x.VaiTro, (IEnumerable<SelectListItem>)ViewBag.VaiTroList, "Chọn vai trò", new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.VaiTro, null, new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <label for="NgayTao">Ngày tạo</label>
                    @Html.TextBoxFor(x => x.NgayTao, new { @class = "form-control", @type = "date" })
                    @Html.ValidationMessageFor(x => x.NgayTao, null, new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <a href="@Url.Action("Index", "Quanlinguoidung")">Quay lại</a>
                    <button type="submit" class="btn btn-primary">Thêm mới</button>
                </div>
            }
        </div>
    </div>
</section>

Group17_MVC (2)/Group17_MVC/Group17_MVC/Views/Quanlinguoidung/Edit.cshtml
@model Group17_MVC.NguoiDung
@{
    ViewBag.Title = "Cập nhật người dùng";
   
}

@section naviheader {
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="@Url.Action("Index", "Admin")">Trang chủ</a>
        </li>
      
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Cập nhật người dùng</a>
        </li>
    </ul>
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Cập nhật người dùng</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Cập nhật</li>
                </ol>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Cập nhật thông tin người dùng</h3>
        </div>
        <div class="card-body">
            @using (Html.BeginForm("Edit", "Quanlinguoidung", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(false)

                <div class="form-group">
                    <label for="MaNguoiDung">Mã người dùng</label>
                    @Html.TextBoxFor(x => x.MaNguoiDung, new { @class = "form-control", @readonly = "readonly" })
                </div>

                <div class="form-group">
                    <label for="HoTen">Tên người dùng</label>
                    @Html.TextBoxFor(x => x.HoTen, new { @class = "form-control", @readonly = "readonly" })
                </div>

                <div class="form-group">
                    <label for="SoDienThoai">Số điện thoại</label>
                    @Html.TextBoxFor(x => x.SoDienThoai, new { @class = "form-control", @readonly = "readonly" })
                </div>

                <div class="form-group">
                    <label for="DiaChi">Địa chỉ</label>
                    @Html.TextBoxFor(x => x.DiaChi, new { @class = "form-control", @readonly = "readonly" })
                </div>

                <div class="form-group">
                    <label for="Email">Email</label>
                    @Html.TextBoxFor(x => x.Email, new { @class = "form-control", @readonly = "readonly" })
                </div>

                <div class="form-group">
                    <label for="VaiTro">Vai trò</label>
                    @Html.DropDownListFor(x => x.VaiTro, (IEnumerable<SelectListItem>)ViewBag.VaiTroList, new { @class = "form-control" })
                </div>

                <div class="form-group">
                   <a href="@Url.Action("Index", "Quanlinguoidung")" class="btn btn-danger">Quay lại</a>
                    <button type="submit" class="btn btn-primary">Cập nhật vai trò</button>
                </div>
            }
        </div>
    </div>
</section>

Group17_MVC (2)/Group17_MVC/Group17_MVC/Views/Quanlinguoidung/Index.cshtml
@model IEnumerable<Group17_MVC.NguoiDung>
@{
    ViewBag.Title = "Index";
    
}
@section naviheader {
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="@Url.Action("Index", "Admin")">Trang chủ</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="@Url.Action("Index", "Quanlisanpham")"> Quản lí sản phẩm</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="@Url.Action("Index", "Quanlinguoidung")">Quản lí người dùng</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="@Url.Action("Index", "Quanlidonhang")">Quản lí đơn hàng</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="@Url.Action("Index", "ThongKe")"> Thống kê</a>
        </li>
    </ul>
}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Quản lí người dùng</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Quản lí người dùng</li>
                </ol>
            </div>
        </div>
    </div>
</section>
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quản Lý Người Dùng</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    <style>
        :root {
            --primary-color: #4CAF50;
            --secondary-color: #2196F3;
            --danger-color: #F44336;
            --background-color: #F5F5F5;
            --text-color: #333;
            --border-color: #E0E0E0;
            --font-family: 'Inter', sans-serif;
        }

        body {
            font-family: var(--font-family);
            margin: 0;
            background-color: var(--background-color);
            color: var(--text-color);
        }

        .container {
            max-width: 1200px;
            margin: auto;
            padding: 20px;
        }

        .header {
            background: var(--primary-color);
            color: #fff;
            padding: 20px;
            border-radius: 5px;
            margin-bottom: 20px;
            text-align: center;
        }

            .header h1 {
                margin: 0;
                font-size: 1.8rem;
            }

        .breadcrumb {
            font-size: 0.875rem;
            margin-top: 5px;
        }

            .breadcrumb a {
                color: #e8f5e9;
                text-decoration: none;
            }

        .action-bar {
            display: flex;
            gap: 10px;
            margin-bottom: 20px;
            
        }

        .search-input {
            flex-grow: 1;
            padding: 10px;
            border: 1px solid var(--border-color);
            border-radius: 5px;
            font-size: 1rem;
        }

        .btn {
            padding: 10px 15px;
            border: none;
            border-radius: 5px;
            font-size: 1rem;
            cursor: pointer;
            display: inline-flex;
            align-items: center;
            gap: 5px;
            transition: background-color 0.3s ease;
        }

        .btn-primary {
            background-color: var(--primary-color);
            color: white;
        }

            .btn-primary:hover {
                background-color: #388e3c;
            }

        .btn-secondary {
            background-color: var(--secondary-color);
            color: white;
        }

            .btn-secondary:hover {
                background-color: #1976d2;
            }

        .btn-danger {
            background-color: var(--danger-color);
            color: white;
        }

            .btn-danger:hover {
                background-color: #d32f2f;
            }

        .table-container {
            overflow-x: auto;
            background-color: white;
            border-radius: 5px;
            padding: 10px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }

        .user-table {
            width: 100%;
            border-collapse: collapse;
            margin: 0;
        }

            .user-table th,
            .user-table td {
                padding: 15px;
                text-align: left;
                border-bottom: 1px solid var(--border-color);
            }

            .user-table th {
                background-color: #f1f8e9;
                color: var(--text-color);
                font-weight: 600;
                text-transform: uppercase;
            }

            .user-table tr:hover {
                background-color: #e8f5e9;
            }

       
        .badge {
            padding: 5px 10px;
            border-radius: 12px;
            font-size: 0.875rem;
            font-weight: bold;
            display: inline-block;
            text-transform: capitalize;
        }

        .badge-admin {
            background-color: #1e88e5;
            color: #ffffff; 
        }

        .badge-customer {
            background-color: #e53935;
            color: #ffffff;
        }

        .badge-success {
            background-color: var(--primary-color);
        }

        .badge-danger {
            background-color: var(--danger-color);
        }

        .action-buttons {
            display: flex;
            gap: 5px;
        }

    </style>
</head>
<body>
    <div class="container">
        
       
        <div class="action-bar">
            @using (Html.BeginForm("Index", "Quanlinguoidung", FormMethod.Get))
            {
                <input type="text"
                       name="searchString"
                       class="search-input"
                       placeholder="Tìm kiếm theo tên hoặc email..."
                       value="@ViewBag.SearchString">
                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-search"></i> Tìm kiếm
                </button>
            }
            <a href="@Url.Action("Index", "Quanlinguoidung")" class="btn btn-secondary">
                <i class="fas fa-sync-alt"></i> Làm mới
            </a>
            <div class="card-tools">
                <a href="@Url.Action("Add", "Quanlinguoidung")" class="btn btn-danger">
                    <i class="fas fa-plus"></i> Thêm mới
                </a>
            </div>
        </div>

        <div class="table-container">
            <table class="user-table">
                <thead>
                    <tr>
                        <th>Mã</th>
                        <th>Tên</th>
                        <th>Điện Thoại</th>
                        <th>Địa Chỉ</th>
                        <th>Email</th>
                        <th>Vai Trò</th>
                        <th>Trạng Thái</th>
                        <th>Hành Động</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.MaNguoiDung</td>
                            <td>@item.HoTen</td>
                            <td>@item.SoDienThoai</td>
                            <td>@item.DiaChi</td>
                            <td>@item.Email</td>
                            <td>
                                @if (item.VaiTro == "Admin")
                                {
                                    <span class="badge badge-admin">Quản trị viên</span>
                                }
                                else 
                                {
                                    <span class="badge badge-customer">Khách hàng</span>
                                }
                               
                            </td>
                            <td>
                                @if (((HashSet<string>)ViewBag.LockedAccounts).Contains(item.MaNguoiDung))
                                {
                                    <span class="badge badge-danger">Bị Khóa</span>
                                }
                                else
                                {
                                    <span class="badge badge-success">Hoạt Động</span>
                                }
                            </td>
                            <td>
                                <div class="action-buttons">
                                    <button class="btn btn-primary" title="Cập nhật vai trò"
                                            onclick="location.href='@Url.Action("Edit", "Quanlinguoidung", new { id = item.MaNguoiDung })'">
                                        <i class="fas fa-edit"></i>
                                    </button>
                                    @if (((HashSet<string>)ViewBag.LockedAccounts).Contains(item.MaNguoiDung))
                                    {
                                        <button class="btn btn-success" title="Mở khóa"
                                                onclick="location.href='@Url.Action("UnlockAccount", "Quanlinguoidung", new { id = item.MaNguoiDung })'">
                                            <i class="fas fa-unlock"></i>
                                        </button>
                                    }
                                    else
                                    {
                                        <button class="btn btn-danger" title="Khóa"
                                                onclick="location.href='@Url.Action("LockAccount", "Quanlinguoidung", new { id = item.MaNguoiDung })'">
                                            <i class="fas fa-lock"></i>
                                        </button>
                                    }
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>